theme: jekyll-theme-cayman
title: Gemstone.IO
description: GPA Gemstone IO Library
github:
  repository_name: Gemstone.IO
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji